version: "3.8"
services:

  merchant-service-api:
    container_name: "Merchant-Service-api"
    build: ./MerchantService
    environment:
      - POSTGRES_HOST=merchant-service-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=merchant_db
      - ENVIRONMENT=dev

    ports:
      - "8001:8000"
    volumes:
      - ./MerchantService/src:/app/src
    depends_on:
      - merchant-service-db


  merchant-service-db:
    container_name: "Merchant-Service-db"
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=merchant_db

    volumes:
      - merchant-service-db-data:/var/lib/postgresql/data
      - ./MerchantService/MigrationScript:/docker-entrypoint-initdb.d/

volumes:
  merchant-service-db-data:






  