version: "3.8"
services:
  # Order Service
  order-service:
    build: ./OrderService
    container_name: "order-service"
    ports:
      - "8000:8000"
    depends_on:
      - order-database-host
      - rabbitmq
    volumes:
      - ./OrderService/src:/app

  order-database-host:
    image: postgres
    container_name: "order-database-host"
    environment:
      - POSTGRES_USER=${ORDER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ORDER_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ORDER_POSTGRES_DB}
    volumes:
      - order-database-data:/var/lib/postgresql/data
      - ./OrderService/MigrationScript:/docker-entrypoint-initdb.d/
  # / Order Service

  rabbitmq:
    image: rabbitmq:3.9.8-management
    container_name: "rabbitmq"
    hostname: rabbitmq
    ports:
      - "8080:15672"

volumes:
  order-database-data:
