version: "3.8"
services:

  buyer:
    build: ./src
    container_name: "buyer_container"
    ports: 
      - "8000:8000"
    depends_on:
      - buyer_db
    volumes:
      - ./src:/app

  test-processor:
    build: ./TestProcessor
    depends_on:
      - buyer
      - rabbitmq
      

  rabbitmq:
    image: rabbitmq:3.9.8-management
    #image: rabbitmq:3.8-management-alpine
    ports: 
      - "5672:5672"     # amqp protocol port
      - "15672:15672"   # http port


  buyer_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Buyer
    volumes:
      - buyer_db-data:/var/lib/postgresql/data
      - ./migration_scripts:/docker-entrypoint-initdb.d/

volumes:
  buyer_db-data: