version: "3.8"
services:
  buyer:
    build: ./src
    container_name: "buyer_container"
    ports:
      - "8002:8002"
    depends_on:
      - buyer_db
    volumes:
      - ./src:/app

  buyer_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Buyer
    volumes:
      - buyer_db-data:/var/lib/postgresql/data
      - ./migration_scripts:/docker-entrypoint-initdb.d/

volumes:
  buyer_db-data:
